CREATE DATABASE IF NOT EXISTS poem_analysis default charset utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE POEM(
   ID VARCHAR(32) NOT NULL,
	 TITLE VARCHAR(100) NULL,
   DYNASTY VARCHAR(100) NULL,
	 AUTHOR VARCHAR(100) NULL,
   CONTENT TEXT NULL,
	 EXTEND VARCHAR(100),
	 GMT_CREATE datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	 GMT_UPDATE datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   PRIMARY KEY ( ID ),
	 UNIQUE (TITLE,DYNASTY,AUTHOR)
);

CREATE TABLE POET(
   ID VARCHAR(32) NOT NULL,
   DYNASTY VARCHAR(100) NULL,
	 NAME VARCHAR(100) NULL,
   INTRODUCTION TEXT NULL,
	 EXTEND VARCHAR(100),
	 GMT_CREATE datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	 GMT_UPDATE datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   PRIMARY KEY ( ID ),
	 UNIQUE (DYNASTY,NAME)
);